### PR TITLE
Refactor File Structure

### PR DESCRIPTION
**Pull request by codewithvk**
Issue #4 
PR  #16 

@yashrsharma44 Please review the code!!

### CODE REVIEW

**Review by yashrsharma44 — COMMENTED** [review]
Can you remove the `vis` folder?

**Comment by codewithvk** [comment]
@yashrsharma44 sure, wait just second

**Review by yashrsharma44 — CHANGES_REQUESTED** [review]
Hi @codewithvk thanks for the changes!

Currently, we have now added linting feature for keeping a regular style of coding. Can you run - 
* `eslint "**/*.js" --ignore-pattern node_modules/ --fix`
* `prettier --write "**/*.js"`

This will make sure all the tests pass

**Comment by codewithvk** [comment]
@yashrsharma44  Where need to run command I means path?

and do you want to vis folder permanently remove?

**Comment by yashrsharma44** [comment]
> @yashrsharma44 Where need to run command I means path?

Skip this. Instead pull the changes from master and rebase your branch if you haven't. 

> and do you want to vis folder permanently remove?

Yup, delete this.

**Comment by codewithvk** [comment]
Capture

can you help me with this issue?

**Comment by yashrsharma44** [comment]
Check for multiple `.git` files in your repository. Share the output with me

**Review by yashrsharma44 — APPROVED** [review]
Looks good, just run the app locally and let me know about it.

**Comment by codewithvk** [comment]
it's gonna not work for refactoring.  I think now difficult to refactor the entire codebase.

**Pull request closed without merging**
