### PR TITLE
Added 2 Graph Traversal Algorithm under issue 6

### PR DESCRIPTION
**Pull request by Debanjan2001**
I have created two files named "toposort_cycle_detection.js"  and "findConnectedComponents.js" for the algorithms.  I have also created a folder named "testfiles" under which there are test1.json and test2.json for sample testcases of the two respective algos. Their output will be automatically stored in output.json when you run the code.

### CODE REVIEW

**Comment by yashrsharma44** [comment]
cc @Biswajitghosh98

**Review by Biswajitghosh98 — CHANGES_REQUESTED** [review]
@Debanjan2001 LGTM ! Just remove the output.json files and we'll be good to merge

**Comment by yashrsharma44** [comment]
@Debanjan2001 
Github Tip:
You can add `Fixes #6` and github automatically closes that issue when this is merged

**Comment by Debanjan2001** [comment]
@Biswajitghosh98 Ok I have removed the file "output.json".

@yashrsharma44 Thank you for the tip. I think Aaditya is also working on this issue. So I will pass on this info.

**Pull request merged**
