### PR TITLE
Added ESLint and Prettier GitHub Actions

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #14

### CODE REVIEW

**Comment by yashrsharma44** [comment]
Could you also add in instructions in a new `CONTRIBUTING.md` file explaining the instructions how to configure the linter/prettier in the local computer? That would be helpful for contributors to use them locally, and have passing tests in the CI.

**Comment by yashrsharma44** [comment]
Did you add in the `eslint` in the `package.json`? That way, it would be **_automatically installed_**, rather than asking users to install them. Same for `prettier`.

**Review by yashrsharma44 — APPROVED** [review]
Looks awesome! Thanks @iamrajiv for the work!
Let me cc @Biswajitghosh98 if he wants to add in anything?

**Comment by Biswajitghosh98** [comment]
@yashrsharma44 LGTM. 
Great work @iamrajiv !

**Pull request merged**
