### PR TITLE
File Structure

### PR DESCRIPTION
**Pull request by codewithvk**
Review it so I Can re-arrange it.
issue #4

### CODE REVIEW

**Review by yashrsharma44 — CHANGES_REQUESTED** [review]
Great idea to first discuss the changes expected :muscle: 
Couple of changes - 
* You **can** remove the `vis` folder.
* Can you move the `graph_base.js` to DS/Algo folder?
* Also make sure all the folders are **lowercase**

Rest looks awesome.

**Comment by codewithvk** [comment]
@yashrsharma44 lowercase means Foldername in lowercase?

**Comment by codewithvk** [comment]
File_Structure

**Comment by yashrsharma44** [comment]
> @yashrsharma44 lowercase means Foldername in lowercase?

Yeah.

Looks great, you can move forward with this

**Pull request closed without merging**
