### PR TITLE
Check bipartite graph

### PR DESCRIPTION
**Pull request by devartstar**
From the Adjacency list of vertices obtained from the GraphBase file...coded the logic for checking whether the given graph is 
 Bipartite graph or not.

### CODE REVIEW

**Review by Biswajitghosh98 — APPROVED** [review]

**Comment by Biswajitghosh98** [comment]
@devartstar Add screenshots of test outputs and we'll be good to merge

**Comment by devartstar** [comment]
ScreenShot of some Test Cases for checking if a given Graph in form of Adjacency list is Bipartite or not -
TestCase1
TestCase2
TestCase3

**Comment by Biswajitghosh98** [comment]
cc @yashrsharma44

**Review by yashrsharma44 — APPROVED** [review]
LGTM!!

**Pull request merged**
