### PR TITLE
Adding the code for Eulerian graph

### PR DESCRIPTION
**Pull request by 130sayan**

### CODE REVIEW

**Comment by 130sayan** [comment]
@Biswajitghosh98 please check this. I am not able to understand this one check fail.

**Comment by yashrsharma44** [comment]
The check fail is unrelated

**Comment by 130sayan** [comment]
Thank you @yashrsharma44 .Please check the pull request.

**Comment by yashrsharma44** [comment]
@130sayan Add screenshots of test outputs and we'll be good to merge

**Comment by 130sayan** [comment]
Screenshot from 2020-12-10 18-18-47
Screenshot from 2020-12-10 18-19-25
@yashrsharma44 please check

**Review by Biswajitghosh98 — APPROVED** [review]

**Comment by Biswajitghosh98** [comment]
LGTM !
cc @yashrsharma44

**Review by yashrsharma44 — APPROVED** [review]
LGTM!!

**Pull request merged**
